### PR TITLE
Rm fix plot

### PR DESCRIPTION
**Pull request by rmarabini**
Fix plot in viewer:

1) now sequences star in 1 (not in 0)
2) average and sts code has wrong when the number of sequences were different from all
3) set mpi=8 in tests
4) increase version number
5) remove code duplication

### CODE REVIEW

**Comment by mmmtnez** [comment]
Hi Roberto,

all the tests fail in my case with 8 MPIs, only 1 is allowed. Otherwise maybe I need a special configuration/variable/etc that I do not have.

**Comment by mmmtnez** [comment]
Except the issue with MPIs, there are not other problems and tests run OK. However I would recomend to comment the line 197 of viewer_search_fit to avoid printing the sqlCommand.

**Comment by rmarabini** [comment]
hi @mmmtnez ,

    I do not undertand why MPI does not work for you. Can you try the following. Edit the file  hosts.conf

very likely you have the line

PARALLEL_COMMAND = mpirun   --bind-to core --map-by sequential -np %_(JOB_NODES)d %_(COMMAND)s

chage it by

PARALLEL_COMMAND = mpirun  --bind-to none -np %_(JOB_NODES)d %_(COMMAND)s

and check if the test work

**Comment by mmmtnez** [comment]
To finish I would recommend another suggestion, move the protocol in the model building menu from Rigid fitting to Flexible fitting  in phenix/protocols.conf like this:

@@ -13,11 +13,11 @@ Model building = [
        {"tag": "section", "text": "Initial model", "icon": "bookmark.png", "children": [
        ]},
        {"tag": "section", "text": "Rigid fitting", "icon": "bookmark.png", "children": [
-       {"tag": "protocol", "value": "PhenixProtRunDockInMap",   "text": "default"},
-       {"tag": "protocol", "value": "PhenixProtSearchFit",   "text": "default"}
+       {"tag": "protocol", "value": "PhenixProtRunDockInMap",   "text": "default"}
        ]},
        {"tag": "section", "text": "Flexible fitting", "icon": "bookmark.png", "children": [
-       {"tag": "protocol", "value": "PhenixProtRunRSRefine",   "text": "default"}
+       {"tag": "protocol", "value": "PhenixProtRunRSRefine",   "text": "default"},
+       {"tag": "protocol", "value": "PhenixProtSearchFit",   "text": "default"}
        ]},


The file thus has this final aspect:

[PROTOCOLS]
Protocols SPA = [
	{"tag": "section", "text": "Tools", "openItem": "False", "children": [
	  {"tag": "protocol_group", "text": "Calculators", "openItem": "False", "children": [
	    {"tag": "protocol", "value": "PhenixProtRunSuperposePDBs",   "text": "default"}
	  ]}
	]}]
Model building = [
	{"tag": "section", "text": "Imports", "icon": "bookmark.png", "children": [
	]},
	{"tag": "section", "text": "Preprocess map", "icon": "bookmark.png", "children": [
	]},
	{"tag": "section", "text": "Initial model", "icon": "bookmark.png", "children": [
	]},
	{"tag": "section", "text": "Rigid fitting", "icon": "bookmark.png", "children": [
	{"tag": "protocol", "value": "PhenixProtRunDockInMap",   "text": "default"}
	]},
	{"tag": "section", "text": "Flexible fitting", "icon": "bookmark.png", "children": [
	{"tag": "protocol", "value": "PhenixProtRunRSRefine",   "text": "default"},
	{"tag": "protocol", "value": "PhenixProtSearchFit",   "text": "default"}
	]},
	{"tag": "section", "text": "Validation", "icon": "bookmark.png", "children": [
	{"tag": "protocol", "value": "PhenixProtRunEMRinger",   "text": "default"},
	{"tag": "protocol", "value": "PhenixProtRunMolprobity",   "text": "default"},
	{"tag": "protocol", "value": "PhenixProtRunValidationCryoEM",   "text": "default"}
	]},
	{"tag": "section", "text": "Tools-Calculators", "icon": "bookmark.png", "children": [
	{"tag": "protocol", "value": "PhenixProtRunSuperposePDBs",   "text": "default"}
	]},
	{"tag": "section", "text": "Others", "icon": "bookmark.png", "children": [
	]}
	]

**Comment by rmarabini** [comment]
hi @mmmtnez,

 I am OK with the modification suggested for file protocols.conf . Please commit it and merge :-)

    thanks

**Review by mmmtnez — APPROVED** [review]

**Pull request merged**
